version: '3'
services:
  postgres:
    image: 'haoyudong/postgres:latest'
    restart: always
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=root
    ports:
      - '5432:5432'
    volumes:
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
  server:
    # image: 'haoyudong/todo-example_server:latest'
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - '5001:5001'
  # client:
  #   # image: 'haoyudong/todo-example_client:latest'
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - '80:80'
  #   depends_on:
  #     - server
